service: example-v2

plugins:
  localPath: '../../../'
  modules:
    - serverless-plugin-swagger-ui

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

custom:
  swaggerUi:
    s3Bucket: serverless-plugin-swagger-ui-example-v2
    exportType: swagger
    accepts: application/json
    swaggerUiConfig:
      supportedSubmitMethods: []

functions:
  example:
    handler: functions/example.handler
    events:
      - http:
          method: get
          path: example

resources:
  Resources:
    S3BucketApiDocs:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.swaggerUi.s3Bucket}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
    S3BucketPolicyApiDocs:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: S3BucketApiDocs
        PolicyDocument:
          Statement:
            - Action:
                - s3:GetObject
              Effect: Allow
              Resource:
                Fn::Sub: arn:aws:s3:::${S3BucketApiDocs}/*
              Principal: '*'
